dist: xenial
language: python
python: 3.7

install:
  - pip install -r requirements.txt

# Build steps
script:
  - python xml2jupyter.py 
#  - python xml2jupyter.py config_biorobots.xml test_user_params.py
#  - cd tests
#  - python ../xml2jupyter.py ../config_biorobots.xml ../test_user_params.py

notifications:
  email:
    recipients:
      - randy.heiland@gmail.com
    on_success: always # default: change  (always, never)
    on_failure: always # default: always
